name: streakify
description: A habit streak tracker with a home widget (prototype).
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  home_widget: ^0.8.1
  shared_preferences: ^2.3.0
  uuid: ^4.4.0
  intl: ^0.18.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.68.0
  confetti: ^0.7.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  
  # Data export
  csv: ^6.0.0
  excel: ^4.0.3
  encrypt: ^5.0.1
  
  # State management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.4.0
  firebase_analytics: ^10.7.0
  firebase_remote_config: ^4.3.0
  
  # In-app purchases
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.3.0+18
  in_app_purchase_storekit: ^0.3.6+7
  
  # Onboarding and help
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.0.0
  introduction_screen: ^3.1.12
  showcaseview: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Code generation
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.0
  
  # Testing
  mockito: ^5.4.0

flutter:
  uses-material-design: true