name: streakify
description: A habit streak tracker with a home widget (prototype).
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  home_widget: ^0.8.1
  shared_preferences: ^2.3.0
  uuid: ^4.4.0
  intl: ^0.18.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.68.0
  confetti: ^0.7.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  shimmer: ^3.0.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true